### ISSUE TITLE
cli50 keeps indicating that a newer version of cs50/cli:latest is available

### ISSUE THREAD

**Issue by dmalan** [cs50/cli50#105]
E.g., adding

```
            print(digest)
            print(RepoDigest)
```

below https://github.com/cs50/cli50/blob/0f313f3136fd557ef7b8217c116a76395434a057/cli50/__main__.py#L185 results in output like

```
$ cli50
sha256:f3809a9479eafe7e3bc200da6bb48d0660333f05dc63ef652ae4b8f7b19d7496
cs50/cli@sha256:8b809e8a270af188ae5713e811d2dd05c44d6ceefdf8d558c400959956ee8043
```

wherein the hashes don't match. But updating via `cli50` (or running `docker pull cs50/cli:latest`) yields:

```
$ docker pull cs50/cli
Using default tag: latest
latest: Pulling from cs50/cli
Digest: sha256:8b809e8a270af188ae5713e811d2dd05c44d6ceefdf8d558c400959956ee8043
Status: Image is up to date for cs50/cli:latest
docker.io/cs50/cli:latest
```

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cli50/commit/11feb4eddd541ba1428c4e57b54823f3638ff555](https://github.com/cs50/cli50/commit/11feb4eddd541ba1428c4e57b54823f3638ff555)
