### ISSUE TITLE
cli50 command is not working on macOS 12 (not pulling docker image)

### ISSUE THREAD

**Issue by ehzawad** [cs50/cli50#107]
![Screen Shot 2022-01-19 at 11 43 53 PM](https://user-images.githubusercontent.com/12381692/150185527-c4f1064e-d0ac-472f-8a25-ac1eb311cb70.png)

**Comment by rongxin-liu** [comment]
Thanks for reporting. Please run `pip3 install cli50 --upgrade` now and try again.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cli50/commit/37372a6f93ce6786dac97d35ff1555efa6557d72](https://github.com/cs50/cli50/commit/37372a6f93ce6786dac97d35ff1555efa6557d72)

**Comment by ehzawad** [comment]
> Thanks for reporting. Please run `pip3 install cli50 --upgrade` now and try again.

It's working now. Thank you too to get it fixed!
