### ISSUE TITLE
cli50 hangs if port is in use

### ISSUE THREAD

**Issue by dmalan** [cs50/cli50#108]
This line currently hangs if, e.g., port 5000 is in use:

https://github.com/cs50/cli50/blob/4b0f08a56567556f3e829713707437b43a0c0833/cli50/__main__.py#L262-L264

Can see symptom by running `docker` manually as follows (with some process already bound to TCP 5000):

```
$ docker run --detach --env WORKDIR=/mnt --interactive --label cli50 --rm --security-opt seccomp=unconfined --tty --volume /Users/malan/cs50.ly:/mnt --workdir /mnt --expose 5000 --publish 5000:5000  cs50/cli:latest bash --login
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
a201cd887381690cebdb239fa08c6f5c5dcd871ee1b9cb0fb27f74db9d5fd73e
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use.
```

The above indeed hangs, without returning the user to a prompt. If you omit `--detatch`, you get this instead:

```
$ docker run --env WORKDIR=/mnt --interactive --label cli50 --rm --security-opt seccomp=unconfined --tty --volume /Users/malan/cs50.ly:/mnt --workdir /mnt --expose 5000 --publish 5000:5000  cs50/cli:latest bash --login 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
$ echo $?
125
```

I'm currently using an M1 iMac, but problem seems to relate to port, not the WARNING.

**Comment by rongxin-liu** [comment]
Now it is happening to me as well (macOS Monterey). Are you using macOS Monterey? 

It wasn't happen to me when my laptop was on macOS Big Sur.

**Comment by dmalan** [comment]
Indeed, Monterey this time on x86_64. Any open issues on Docker's end already perhaps? Want to open if not?

**Comment by rongxin-liu** [comment]
Well actually, this is not necessarily a Docker bug. Port 5000 was indeed in-use already by Monterey's control center:

```
[~]$ netstat -vanp tcp | grep 5000
tcp6       0      0  *.5000                 *.*                    LISTEN      131072 131072    402      0 0x0100 0x00000006
tcp4       0      0  *.5000                 *.*                    LISTEN      131072 131072    402      0 0x0100 0x00000006
[~]$ lsof -i tcp:5000 
COMMAND   PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ControlCe 402 rongxinliu   19u  IPv4 0xa193dc4706ffe7eb      0t0  TCP *:commplex-main (LISTEN)
ControlCe 402 rongxinliu   20u  IPv6 0xa193dc3d6f120753      0t0  TCP *:commplex-main (LISTEN)
```

**Comment by rongxin-liu** [comment]
Though for cli50, we could use `socket` library to determine if a given port is already occupied and perhaps find the next available port automatically for user:
```
import socket

def is_port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('localhost', port)) == 0
```
Then we can do something like:
```
while(is_port_in_use(port)):
    port += 1
```
Or have cli50 inform the user about it and let users specify some other ports to use.

**Comment by rongxin-liu** [comment]
[https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/](https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/)
