### ISSUE TITLE
Make output is not colored

### ISSUE THREAD

**Issue by tlively** [cs50/cli50#16]
When running commands like `make` inside cli50, the output does not have color. I tried replacing the `subprocess.call` line with `pexpect.spawn("docker", ["run"] + options + ["cs50/cli"]).interact()`, which uses a pseudo-tty, but this didn't fix the issue. Colorful output from `make` and friends would be nice for using cli50 in section.

**Comment by tlively** [comment]
Update: The colortest package works as expected, so it's not the case that Python is squashing colors.

**Comment by tlively** [comment]
Update 2: Using clang directly with `-fcolor-diagnostics` produces colors as expected.

**Comment by tlively** [comment]
Update 3: `make` is calling `cc` which is gcc, not clang. This issue is resolved by setting the environments `CC=clang` and `CFLAGS="-fsanitize=integer -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wshadow"` to match the IDE.

**Comment by dmalan** [comment]
Should be fixed in latest ubuntu user-based image!
