### ISSUE TITLE
can't run cli50 on windows 10

### ISSUE THREAD

**Issue by NamelessKing** [cs50/cli50#68]
I am trying to run cli 50 to mount a directory for test and learning purposes but I get this error:

> NamelessKing@DESKTOP-namelessking MINGW64 /e/Users/NamelessKing/docker_mount_test
$ cli50
Using default tag: latest
latest: Pulling from cs50/cli
Digest: sha256:d7abc5ac7f9d557aa25bebaee1234e28722cac153d1a7dc2fe0ea28280d58c0f
Status: Image is up to date for cs50/cli:latest
Traceback (most recent call last):
  File "C:\Users\NamelessKing\AppData\Local\Programs\Python\Python37\Scripts\cli50-script.py", line 11, in <module>
    load_entry_point('cli50==3.0.0', 'console_scripts', 'cli50')()
  File "c:\users\namelessking\appdata\local\programs\python\python37\lib\site-packages\cli50\__main__.py", line 172, in main
    child = pexpect.spawn("docker", ["start", "--attach", "--interactive", container], dimensions=(lines, columns),
AttributeError: module 'pexpect' has no attribute 'spawn'

**Comment by dmalan** [comment]
Sorry about that, @NamelessKing, fixing thanks to @ashenm!
