### ISSUE TITLE
cli50 bash sometimes ignores first letter

### ISSUE THREAD

**Issue by kuelshammer** [cs50/cli50#75]
When I start cli50 it is not possible to enter comands as the first letter is sometimes ignored.

Here I use Cmder as console application:
![git-test](https://user-images.githubusercontent.com/22079931/61353941-442bc200-a871-11e9-904f-24ccb6a164be.gif)

Using cmd it is even worse
![git-test](https://user-images.githubusercontent.com/22079931/61354092-9f5db480-a871-11e9-8655-0df92e7ead95.gif)

I have the lastest docker/cli50 image and did upgrade cli50 via pip.

Max

**Comment by dmalan** [comment]
Hi Max, thanks for the report. That's a curious one! Couple questions:

(1) If you run

```
docker run --detach --interactive --name foo --publish-all --rm --security-opt seccomp=unconfined --tty --workdir /mnt cs50/cli:latest bash --login
docker attach foo
```

do you see that same symptom?

(2) If you save https://gist.github.com/dmalan/6bc2900b99c8974056ff72cc5cc4999e to a file called `bar.py` and run `python3 bar.py`, do you see that same symptom?

**Comment by ashenm** [comment]
Hi @dmalan, as you suspected the issue lies within the `execvp` call which unfortunately on Windows systems resolves to an equivalent to the following; leaving the both child process and the cmd connected.

```python
os.spawnv(os.P_NOWAIT, ...)
os._exit(0)
```

[This](https://github.com/cs50/cli50/pull/76) shall hopefully resolve the issue.

**Comment by kuelshammer** [comment]
Hi @dmalan,
I tried (1) and I get a working console without mounted directory. Using (2) I get the missing first letter again.

Max

**Comment by dmalan** [comment]
Thanks for testing, @kuelshammer. And thanks for digging in, @ashenm. I made a couple tweaks, https://github.com/cs50/cli50/commit/631005c73f23c74ec3fa844e9333b1fb00b25d97, but https://bugs.python.org/msg198599 seems to confirm that was indeed the issue. Version 3.2.1 should now fix!

```
pip3 install cli50 --upgrade
```

**Comment by kuelshammer** [comment]
Thanks, for me `cli50` is working now (in `cmd`and `Cmder`). Max
