### ISSUE TITLE
mount current working directory when logging into a running container

### ISSUE THREAD

**Issue by async-costelo** [cs50/cli50#91]
I'm spinning up a development env on my local machine cuz I wanna try NOT using **cs50 ide**, **cs50 sandbox**, or **cs50 lab**.
I want this environment to be stable for the next activities, that way I won't need to launch any new instances when mounting a directory for **psets**.

Also, I want my git account authenticated [via SSH](https://cs50.readthedocs.io/submit50/#via-ssh). So I don't always input my user & pass every time I use **submit50** or just even **compare50**.

### 1. My case
I already have a running container, and I don't want to delete this (not after the course):

![image](https://user-images.githubusercontent.com/34333555/92600487-3a1f1b00-f2de-11ea-88e4-ccb51d88b003.png)

I'm going to try logging in and hoping it mounts my current working dir. (I'm using VSCode btw):

![image](https://user-images.githubusercontent.com/34333555/92601057-ea8d1f00-f2de-11ea-8f25-5bcf475fd225.png)

Result:

![image](https://user-images.githubusercontent.com/34333555/92601363-4c4d8900-f2df-11ea-819e-688543e96078.png)

### 2. Standard usage
Here is the standard usage of **cli50**

![image](https://user-images.githubusercontent.com/34333555/92601485-756e1980-f2df-11ea-987a-55403dcf699b.png)

...and it launched up a new instance

![image](https://user-images.githubusercontent.com/34333555/92601887-ef9e9e00-f2df-11ea-81e3-ba5e77a7bfec.png)

Have a nice day! :D

**Comment by async-costelo** [comment]
I tried ` cli50 [-l [CONTAINER]] [DIRECTORY]` but still won't mount. Thanks!

**Comment by dmalan** [comment]
`-l` logs you into an already-running container, using whatever directory was mounted in it. Sounds like you want to run just `cli50` in whatever directory you want to work in. As for SSH, see https://cs50.readthedocs.io/cli50/#mount-dotfile!
